version: '3.8'

services:
  maven:
    image: maven:3.9-eclipse-temurin-17
    container_name: maven-builder
    volumes:
      - ./sample-servlet:/usr/src/app
    working_dir: /usr/src/app
    command: mvn clean package

  tomcat:
    image: tomcat:10.1-jdk17
    container_name: tomcat-server
    ports:
      - "8080:8080"
    volumes:
      - ./sample-servlet/target/sample.war:/usr/local/tomcat/webapps/sample.war
    depends_on:
      - maven
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=todo_db
      - DB_USER=todo_user
      - DB_PASSWORD=todo_pass

    db:
      image: mysql:8.0
      container_name: mysql-db
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: todo_db
        MYSQL_USER: todo_user
        MYSQL_PASSWORD: todo_pass
      ports:
        - "3306:3306"
      volumes:
       - db_data:/var/lib/mysql